{
	"extends": [
		"plugin:react/recommended",
		"plugin:react-hooks/recommended"
	],
	"plugins": [
		"@typescript-eslint"
	],
	"settings": {
		"react": {
			"version": "detect"
		}
	},
	"rules": {
		"react/jsx-indent": [
			"error",
			"tab"
		],
		"react/jsx-indent-props": [
			"error",
			"tab"
		],
		"react/jsx-max-props-per-line": [
			"error",
			{
				"maximum": 1,
				"when": "multiline"
			}
		],
		"react/self-closing-comp": "error",
		"react/jsx-props-no-multi-spaces": "error",
		"react/jsx-closing-bracket-location": "error",
		"react/jsx-wrap-multilines": "warn",
		"react/no-unused-prop-types": "warn",
		"react/react-in-jsx-scope": "off",
		"react/display-name": "off",
		"react/prop-types": "off",
		"indent": [
			"error",
			"tab",
			{
				"SwitchCase": 1
			}
		],
		"@typescript-eslint/naming-convention": "off"
	},
	"parserOptions": {
		"project": "./tsconfig.json"
	}
}
